### ISSUE TITLE
PyPI release

### ISSUE THREAD

**Issue by jannisborn** [PaccMann/paccmann_datasets#138]
With `rdkit` now being pypi installable nothing prevents us from releasing pytoda via pypi :)

- twine/pypi setup
- simplifying development installations
- simplifying CI setup in GA workflows
- releasing version 1.0 ? (any thoughts @drugilsberg @C-nit ?)

**Comment by drugilsberg** [comment]
agreed with having a major advance but I would keep the patch in the version `1.0.0`
