### ISSUE TITLE
low GPU utilization

### ISSUE THREAD

**Issue by YoelShoshan** [PaccMann/paccmann_datasets#155]
I've noticed that training (and inference) loops of multiple models that use default pytoda datsets settings have very low GPU utilization.

Initially I thought that it's because people keep num_workers=0 in their configs which makes pytorch DataLoader to only work in a single process. However, after increasing num_workers into any value larger than 0 it crashed.

Initially it was just a matter of few lambda functions in pytoda datasets which multiprocessing doesn't like due to pickling issues (which was pretty easy to fix)
But after that, I kept getting the error which I describe [here](https://github.com/pytorch/pytorch/issues/77159)

Shortly - you get 
"RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method"

Using the suggested solution of setting to 'spawn' does not actually solve the problem.

Using the modification of NOT transferring tensors to the GPU inside pytoda resulted in x5-x20 speedup in training so I think that this is a pretty critical aspect.

I think that device should not be part of the api, and if it is it should at least default to cpu (and have a warning when it's not)

I can prepare an initial PR if you'd like.

edit: @jannisborn pointed me to a related issue: https://github.com/PaccMann/paccmann_datasets/issues/105

**Comment by jannisborn** [comment]
Hi @YoelShoshan,
thanks for the great initiative. I think we can start a refactor that removes the `device` argument from all dataset classes. 

I would leave the return types of the `get_item` methods untouched (so that we still return tensors rather than e.g., SMILES-strings) since the latter would introduce heavy backwards incompatibilities.

**Comment by YoelShoshan** [comment]
@jannisborn I agree - returning (cpu) tensors is perfectly fine

**Comment by jannisborn** [comment]
Addressed in #156
