### ISSUE TITLE
add polymer dataset

### ISSUE THREAD

**Issue by jannisborn** [PaccMann/paccmann_datasets#16]
Add a dataset for polymers that creates an arbitrary tuple of smiles datasets.
- same params as smiles dataset but takes lists for each param, length of list corresponds to amount of smiles dataset.
- Single smiles language object for all of them. 
- We need modification in smiles language to handle start and stop of individual smiles entities like <START_MONOMER> etc (--> `polymer_smiles_language` class?)
- loader returns a tuple, one smiles per dataset

**Comment by drugilsberg** [comment]
Closed by #17
