### ISSUE TITLE
Remove invalid SMILES

### ISSUE THREAD

**Issue by jannisborn** [PaccMann/paccmann_datasets#22]
Atm, the `SMILESDataset` setup fails if there is a single invalid SMILES.

We should do two things:

1. raise a warning whenever an invalid SMILES is encountered. The transforms (like canonicalization) will not apply and the raw SMILES will be tokenized (@jannisborn)
2. Create a script that parses a `.smi` file and removes all invalid SMILES (@drugilsberg).

**Comment by jannisborn** [comment]
@drugilsberg The stage is yours!

**Comment by drugilsberg** [comment]
@jannisborn I suggest to merge #23  and leave this open only to track the script creation.

- [X] raise a warning whenever an invalid SMILES is encountered. The transforms (like canonicalization) will not apply and the raw SMILES will be tokenized (@jannisborn)
- [x] Create a script that parses a .smi file and removes all invalid SMILES (@drugilsberg).

**Comment by jannisborn** [comment]
Agreed, I merged #23

**Comment by jannisborn** [comment]
1. fixed by #23 
2. fixed by #30
