### ISSUE TITLE
_CashDataset has default 1GB size limit

### ISSUE THREAD

**Issue by C-nit** [PaccMann/paccmann_datasets#43]
there is a default file size limit for the cache
>size_limit (int, in bytes) default one gigabyte - approximate size limit of cache.
http://www.grantjenks.com/docs/diskcache/api.html#constants

Not very useful in the case where the data doesn't fit into memory. In case of larger data, a likely error to the user is `KeyError: 0` when starting to iterate.
- There should be a way to pass arguments to the cache instantiation from the inheriting classes `_SmiLazyDataset` and `_CsvLazyDataset` and the uses of these.
- An error should be raised when loading too large data right away.

**Comment by jannisborn** [comment]
Seems reasonable, great that you found that. We could add an argument called `lazy_kwargs` to all dataset classes? This could be passed down all the way to `_CacheDataset` and the error would also be caught there.

**Comment by drugilsberg** [comment]
I think leaving just an argument in the standard **kwargs is much cleaner. That said, the desired behaviour should be to dynamically set the cache size based on the size.
