### ISSUE TITLE
_TableDatset: prevent computation of both standardize and min_max:

### ISSUE THREAD

**Issue by C-nit** [PaccMann/paccmann_datasets#61]
calling `.fit` may be time consuming for larger dataset. Given that `self.standardize` and `self.min_max` are never both true, couldn't we make sure to call only the needed `.fit` function here?

_Originally posted by @jannisborn in https://github.com/_render_node/MDIzOlB1bGxSZXF1ZXN0UmV2aWV3VGhyZWFkMjc2Mzc3NTI4OnYy/pull_request_review_threads/discussion_

**Comment by jannisborn** [comment]
Closing this due to low priority. I'm cleaning up the issue list. We can filter by wontfix label to retrieve those low-priority-issues in the future if necessary
